class Text:
    def __init__ (self):
        
        self.s_1_titles = [
            "The Pilot",
            "The One with the Sonogram at the End",
            "The One with the Thumb",
            "The One with George Stephanopoulos",
            "The One with the East German Laundry Detergent",
            "The One with the Butt",
            "The One with the Blackout",
            "The One Where Nana Dies Twice",
            "The One Where Underdog Gets Away",
            "The One with the Monkey",
            "The One with Mrs. Bing",
            "The One with the Dozen Lasagnas",
            "The One with the Boobies",
            "The One with the Candy Hearts",
            "The One with the Stoned Guy",
            "The One with Two Parts: Part 1",
            "The One with Two Parts: Part 2",
            "The One With All The Poker",
            "The One Where The Monkey Gets Away",
            "The One With The Evil Orthodontist",
            "The One With The Fake Monica",
            "The One With The Ick Factor",
            "The One With The Birth",
            "The One Where Rachel Finds Out"
        ]

        self.s_1_original_airdate =[
            "September 22, 1994", "September 29, 1994", "October 6, 1994",
            "October 13, 1994", "October 20, 1994", "October 27, 1994",
            "November 3, 1994", "November 10, 1994", "November 17, 1994",
            "December 15, 1994", "January 5, 1995", "January 12, 1995",
            "January 19, 1995", "February 9, 1995", "February 16, 1995",
            "February 23, 1995", "February 23, 1995", "March 2, 1995",
            "March 9, 1995", "April 6, 1995", "April 27, 1995",
            "May 4, 1995", "May 11, 1995", "May 18, 1995"
        ]

        self.s_1_summary =[
            'Monica and the gang introduce Rachel to the "real world" after she leaves her fiancé at the altar. Ross struggles with his rediscovered feelings for Rachel.',
            'Ross finds out his estranged lesbian wife and her life partner are going to have his baby.',
            'Phoebe discovers a human thumb floating in her can of soda and gets compensation of $7,000. Chandler starts smoking again.',
            'The girls spy on the sexy politician across the street, while the guys go to a hockey game.',
            'Ross and Rachel wash their laundry together. Joey takes Monica on a fake double date in an attempt to reunite with his ex.',
            "Joey finally gets a film role: Al Pacino's butt double. Chandler dates a woman who already has both a husband and a boyfriend.",
            "During a power outage, Rachel falls for the owner of a lost kitten, a Italian guy, much to Ross's chagrin. Meanwhile, Chandler is trapped in an automated-teller vestibule with a gorgeous model.",
            'Ross and Monica go to the bedside of their dead grandmother, who momentarily returns to life. Chandler questions his sexual persona when a collegue wants to arrange a date for him with another guy.',
            'Monica plans a lovely, quiet Thanksgiving feast in her apartment but her plans go awry. Joey appears on medical posters. Rachel plans to go skiing with her family.',
            "Ross arrives at the New Year's Eve party with his new companion, a monkey named Marcel, who is more compatible with the group than he is.",
            "Chandler's flamboyant romance-novelist mother comes to New York for a visit. Monica and Phoebe cause a traffic accident.",
            "Rachel's Italian boyfriend Paolo hits on Phoebe in the massage parlor.",
            "The girls rebel against Valentine's Day by burning mementos from past relationships. Chandler reunites with an old flame.",
            'Chandler sees Rachel naked. Joey learns that his father is having an affair with a pet mortician, but his mother already knew.',
            "Ross asks Joey for advice on how to talk dirty to women. Monica interviews for a chef's position, but the owner shows up stoned.",
            "Phoebe's twin sister causes confusion and conflict when Joey is attracted to her.",
            'Monica and Rachel squabble over two handsome doctors.',
            "The girls lose money in a poker game with the boys. After getting advice from Monica's aunt, they demand a rematch.",
            "Rachel accidentally lets Ross's pet monkey escape and a search party forms. Then she discovers that her old best friend Mindy is engaged to marry her ex-fiance.",
            "Rachel has a brief encounter with her ex-fiance. Riddled with guilt, she decides to confess her evil sins only to discover that Mindy's been busier than she's let on.",
            "Monica meets her identity thief, who helps her live out her fantasies. Ross's monkey becomes sexually mature and drives everyone crazy.",
            "Monica discovers that she is a cradle snatcher. Ross's ex-wife begins giving birth.",
            'The baby is born, bringing adoration from everyone.',
            "Rachel finds out about Ross's love for her while he is working in China. However, another surprise awaits her as she heads to the airport to meet him."
        ]
        
        self.s_2_titles = [
            "The One With Ross' New Girlfriend",
            "The One With The Breast Milk",
            "The One Where Heckles Dies",
            "The One With Phoebe's Husband",
            "The One With Five Steaks And An Eggplant",
            "The One With The Baby On The Bus",
            "The One Where Ross Finds Out",
            "The One With The List",
            "The One With Phoebe's Dad",
            "The One With Russ",
            "The One With The Lesbian Wedding",
            "The One After The Superbowl, Part 1",
            "The One After The Superbowl, Part 2",
            "The One With The Prom Video",
            "The One Where Ross And Rachel... You Know",
            "The One Where Joey Moves Out",
            "The One Where Eddie Moves In",
            "The One Where Dr. Ramoray Dies",
            "The One Where Eddie Won't Go",
            "The One Where Old Yeller Dies",
            "The One With The Bullies",
            "The One With Two Parties",
            "The One With The Chicken Pox",
            "The One With Barry & Mindy's Wedding"
        ]

        self.s_2_original_airdate = [
            "September 21, 1995", "September 28, 1995", "October 5, 1995",
            "October 12, 1995", "October 19, 1995", "November 2, 1995",
            "November 9, 1995", "November 16, 1995", "December 14, 1995",
            "January 4, 1996", "January 18, 1996", "January 28, 1996",
            "January 28, 1996", "February 1, 1996", "February 8, 1996",
            "February 15, 1996", "February 22, 1996", "March 21, 1996",
            "March 28, 1996", "April 4, 1996", "April 11, 1996",
            "May 2, 1996", "May 9, 1996", "May 16, 1996"
        ]

        self.s_2_summary = [
            "Rachel gets an unpleasant surprise when Ross returns home. Phoebe has varied success when cutting her friends' hair!",
            "Monica goes shopping when Ross's new girlfriend and is too afraid to tell Rachel. Joey is troubled when a fellow after-shave salesman outperforms him on the job.",
            "The downstairs neighbor dies and bequeaths his strange possessions to Monica and Rachel.",
            "Everyone's surprised when Phoebe's husband shows up.",
            "When planning a birthday party for Ross, the six discover money is an issue in life, even among friends.",
            "Joey and Chandler accidentally leave Ben on a bus while babysitting. Phoebe (whose Smelly Cat debuts here) gets fired from her Central Perk singing gig, and is replaced by a professional.",
            "Dramatic developments occur in Ross and Rachel's relationship. Chandler regrets asking Monica to help him lose weight.",
            "Rachel makes a painful discovery concerning Ross. Monica's new boss gives her an impossible task.",
            "Phoebe learns the surprising truth about her father. Ross makes Monica's Christmas party guests miserable. Rachel gets her revenge on Ross.",
            "After some gentle person persuasion, Joey accepts a great acting job. Rachel dates a guy who looks amazingly like Ross.",
            "Carol and Susan prepare for their wedding with help from an uncomfortable Ross.",
            "Ross goes to visit Marcel the Monkey in the San Diego Zoo and finds the simian is pursuing a show-biz career. Joey has a date with a deranged fan. Lembeck won a Best Director Emmy.",
            "Rachel and Monica fight over Jean-Claude Van Damme. Chandler dates a girl he went to elementary school with, with a surprising outcome. Lembeck won a Best Director Emmy.",
            "Monica's old home video elicits the true feelings Ross has for Rachel. Joey gives Chandler a gift.",
            "Ross and Rachel encounter romantic obstacles. Monica falls for a handsome older doctor. Chandler and Joey have new lazy chairs and do not want to get up from them.",
            "Chandler catches Joey licking a spoon and replacing it in the drawer, and a major fight ensues. Monica's parents find out about her new boyfriend.",
            "Joey and Chandler pine for each other but neither will admit it. Chandler gets a new roommate. A record company asks Phoebe to make a Smelly Cat music video.",
            "Joey's soap character looks set to be killed off after Joey makes some contentious remarks to a fan magazine. Monica and Richard have their first argument.",
            "Chandler battles to get rid of his annoying new roommate and have Joey, who's feeling the crunch of unemployment and mounting debt, move back in. The girls discover a book on personal empowerment.",
            "Impressionable Phoebe becomes depressed when it dawns on her that some movies don't end happily. Richard bonds with Chandler and Joey at a basketball game.",
            "Chandler and Ross are intimidated by two bullies who take over the friends' Central Perk sofa. Phoebe meets her long-lost family.",
            "Rachel gets a real surprise when her parents show up at her birthday party.",
            "When Phoebe catches chicken pox, her chances for romance with an ex-love are nearly ruined. Rachel is intrigued by Phoebe's ex-love sailor suit wanting Ross to have one as well. Monica feels she may be too neurotic for straight-arrow Richard.",
            "Rachel is a bridesmaid at her ex-fiance's wedding. Monica and Richard's relationship is jeopardized when the subject of children arises."
        ]
    
        self.s_3_titles = [
            "The One With The Princess Leia Fantasy",
            "The One Where No One's Ready",
            "The One With The Jam",
            "The One With The Metaphorical Tunnel",
            "The One With Frank Jr.",
            "The One With The Flashback",
            "The One With The Race Car Bed",
            "The One With The Giant Poking Device",
            "The One With The Football",
            "The One Where Rachel Quits",
            "The One Where Chandler Can't Remember Which Sister",
            "The One With All The Jealousy",
            "The One Where Monica & Richard Are Friends",
            "The One With Phoebe's Ex-Partner",
            "The One Where Ross & Rachel Take A Break",
            "The One With The Morning After",
            "The One Without The Ski Trip",
            "The One With The Hypnosis Tape",
            "The One With The Tiny T-Shirt",
            "The One With The Dollhouse",
            "The One With A Chick And A Duck",
            "The One With The Screamer",
            "The One With Ross's Thing",
            "The One With The Ultimate Fighting Champion",
            "The One At The Beach"
        ]

        self.s_3_original_airdate = [
            "September 19, 1996", "September 26, 1996", "October 3, 1996",
            "October 10, 1996", "October 17, 1996", "October 31, 1996",
            "November 7, 1996", "November 14, 1996", "November 21, 1996",
            "December 12, 1996", "January 9, 1997", "January 16, 1997",
            "January 30, 1997", "February 6, 1997", "February 13, 1997",
            "February 20, 1997", "March 6, 1997", "March 13, 1997",
            "March 27, 1997", "April 10, 1997", "April 17, 1997",
            "April 24, 1997", "May 1, 1997", "May 8, 1997",
            "May 15, 1997"
        ]

        self.s_3_summary = [
            "Ross's secret fantasy doesn't stay secret for long after he confides in Rachel. Chandler begins to rekindle his relationship with ex-girlfriend Janice.",
            "Ross gets riled when his friends fail to be ready on time for a museum fundraiser where he's giving a speech.",
            "Monica becomes obsessed with making jam as a means of getting over Richard. Still feeling unfulfilled, she decides she wants to having a baby and visits a sperm bank.",
            "Ross and Rachel encourage Chandler to " + '"go through the tunnel"' + " and commit to Janice. Ross worries when his son plays with a girl's doll and tries frantically to substitute masculine toys.",
            "Phoebe invited her half-brother Frank Jr. to visit. Ross makes a list of famous women he'd like to date.",
            "After Janice asks whether they've ever dated each other, the friends reminisce about a time three years ago and some dark secrets are revealed.",
            "When returning a misdelivered bed back to the store, Monica and Joey catch Janice passionately kissing her ex-husband in the back room.",
            "When Phoebe believes she's killed the ugly naked guy across the street from Rachel and Monica, Joey constructs a long poking device. Chandler confronts Janice.",
            "It's Thanksgiving and the friends start a game of football that reveals some major rivalries and prods a rematch that has serious implications for the roast turkey!",
            "After quitting her Central Perk gig, Rachel worries she'll be jobless long-term. Joey's job selling Christmas trees upsets Phoebe, who becomes distressed over leftover trees.",
            "A handsome stranger offers Rachel a fashion-buying job. Chandler forgets which of Joey's sisters he fooled around with after getting drunk at Joey's birthday.",
            "Ross becomes obsessively jealous of Rachel's sexy new co-worker Mark and is convinced he is flirting with Rachel. Monica is smitten with a sexy busboy.",
            "Monica and ex-boyfriend Richard meet by chance - and the lunch they go to leads to something more.",
            "Phoebe's ex-singing partner Leslie wants to use Smelly Cat for a cat-litter ad. Chandler dates a beautiful woman with an artificial leg... and a tie to Joey.",
            "Ross and Rachel decide to go on a break. Phoebe becomes involved with a foreign diplomat.",
            "Unaware of Ross's one-night stand with another woman, Rachel visits him to declare her undying love.",
            "Rachel asks everyone to go on a ski trip... except Ross. Chandler is particularly traumatized by the Ross/Rachel breakup, which reminds him of his parents' divorce.",
            "Chandler uses a hypnosis tape to quit smoking. Unbeknownst to him, it's aimed only at women. Phoebe freaks when her brother wants to wed a woman twice his age.",
            "Ross is upset when Rachel returns his belongings. Monica dates a millionaire she considers funny, nice and yet not quite her dream man.",
            "Monica inherits an exquisite dollhouse from her aunt. Joey winds up in bed with his leading lady. Rachel's boss dates Chandler.",
            "Monica is ecstatic when her millionaire friend Pete buys a restaurant and wants her as head chef. Joey buys Chandler a chick - a live baby chicken and later a live duck.",
            "Joey's play gets terrible reviews. Ross tries to convince Rachel her date is psychotic.",
            "Ross discovers a strange growth on his buttocks. Phoebe dates a firefighter and a teacher.",
            "Monica begs Pete to stop fighting after he is beaten up. Chandler is unnerved when his boss slaps his butt. Ross starts dating a new woman.",
            "Phoebe invites the group to her client's beach house. Rachel tricks Ross's new girlfriend into shaving her head."
        ]

        self.s_4_titles = [
            "The One With The Jellyfish",
            "The One With The Cat",
            "The One With The Cuffs",
            "The One With The Ballroom Dancing",
            "The One With Joey's New Girlfriend",
            "The One With The Dirty Girl",
            "The One Where Chandler Crosses The Line",
            "The One With Chandler In A Box",
            "The One Where They're Going To Party",
            "The One With The Girl From Poughkeepsie",
            "The One With Phoebe's Uterus",
            "The One With The Embryos",
            "The One With Rachel's Crush",
            "The One With Joey's Dirty Day",
            "The One With All The Rugby",
            "The One With The Fake Party",
            "The One With The Free Porn",
            "The One With Rachel's New Dress",
            "The One With All The Haste",
            "The One With All The Wedding Dresses",
            "The One With The Invitation",
            "The One With The Worst Best Man Ever",
            "The One With Ross's Wedding, Part 1",
            "The One With Ross's Wedding, Part 2"
        ]

        self.s_4_original_airdate = [
            "September 25, 1997", "October 2, 1997", "October 9, 1997",
            "October 16, 1997", "October 30, 1997", "November 6, 1997",
            "November 13, 1997", "November 20, 1997", "December 11, 1997",
            "December 18, 1997", "January 8, 1998", "January 15, 1998",
            "January 29, 1998", "February 5, 1998", "February 26, 1998",
            "March 19, 1998", "March 26, 1998", "April 2, 1998",
            "April 9, 1998", "April 16, 1998", "April 23, 1998",
            "April 30, 1998", "May 7, 1998", "May 7, 1998"
        ]

        self.s_4_summary = [
            "Ross falls asleep while reading Rachel's 18-page letter. When confronted by her, he pretends to agree with what she wrote. Monica gets stung by a jellyfish and must resort to drastic measures.",
            "Phoebe believes her adoptive mother's spirit inhabits a stray cat. Joey finds the experience of selling his entertainment center not entertaining at all. Monica finally gets to date the big man on her high school campus.",
            "Monica " + '"pulls a Monica"' " when she caters her mother's party. Chandler gets himself locked into a compromising position with Rachel's boss.",
            "The girls get an eviction notice and Joey comes to their rescue by agreeing to give the building superintendent dancing lessons.",
            "Ross and Rachel continue their power games to make each other jealous. Chandler falls hard for Joey's new girlfriend Kathy.",
            "Ross's beautiful new girlfriend has a disgusting secret. Chandler gets closer to Kathy and buys her a pricey birthday gift. Rachel proudly completes a crossword puzzle without help.",
            'Chandler kisses Kathy after thinking Joey has lost interest in her. Encouraged by an awed Phoebe, Ross debuts his keyboard "sound" in public.',
            "Still angry over the Kathy kiss, Joey punishes Chandler by shutting him in a box on Thanksgiving. Monica gets a surprise when she visits the eye doctor.",
            "When the guys try to be wild and crazy, they reluctantly realize they'd rather act like adults. Monica writes a scathing restaurant review - and gets a job offer as a result.",
            "Ross debates whether to date a faraway beauty or a less desirable woman who lives nearby. Chandler tries to set up a date for Rachel with some co-workers.",
            "Phoebe's half-brother Frank Jr. returns with exciting news - and asks a huge favor of Phoebe. Ross gets Joey a job as a museum tour guide.",
            "Phoebe's uterus is put to the ultimate test. A seemingly harmless game between the guys and the girls escalates into a full-blown contest to see which pair knows more personal data about the other.",
            "Rachel schemes to get a handsome client to ask her on a date. Chandler's jealousy causes problems with his girlfriend.",
            "On Joey's first day on a major movie, one of Hollywood's legendary stars finds him in a compromising position in his trailer. Rachel regrets asking Ross for a favor when it sparks a new romance.",
            "Chandler's abrasive ex-girlfriend Janice reappears. Monica finds a mysterious switch in Joey and Chandler's old apartment. Ross tries to impress Emily by playing rugby.",
            "To become better acquainted with her crush Joshua, Rachel inadvertently thwarts Ross's plans. Phoebe's pregnancy cravings evoke a sympathetic response from Joey.",
            "Chandler and Joey are glued to their TV after discovering an unscrambled adult cable channel. Monica helps Ross tell his girlfriend he loves her. Phoebe gets some surprising pregnancy news.",
            "Rachel takes a provocative pose to get Joshua into a romantic mood - but her plans go awry. Chandler and Joey are at odds to persuade Phoebe to name one of her triplets after them.",
            "Drastic developments blight Ross's relationship with Emily. Monica and Rachel try to win back their old apartment, much to Chandler and Joey's delight.",
            "Distraught over Ross's engagement, Rachel takes Joshua aside and suggests they also get married. Chandler forces Joey to go to a sleep clinic to stop his loud snoring. Monica and Phoebe get obsessed to wedding dresses after trying on Emily's wedding dress.",
            "Rachel and Ross each reminisce about when they used to date each other. Everyone is disappointed when Rachel decides not to attend the wedding in England.",
            "When Joey's duck swallows Ross' wedding ring, he is worried he'll have to sacrifice his beloved fowl to retrieve it.",
            "Ross tries to encourage Rachel to come to his wedding. Arriving in London, Joey and Chandler go sightseeing but Joey's overly enthusiastic behavior compels Chandler to go off on his own.",
            "Back in New York, Rachel realizes her feelings for Ross are stronger than ever and rushes off to the airport as wedding time nears. After a drunken guest mistakes Monica for Ross's mother, She and Chandler console each other and start their romantic journey."
        ]

        self.s_5_titles = [
            "The One After Ross Says Rachel",
            "The One With All The Kissing",
            "The One Hundredth",
            "The One Where Phoebe Hates PBS",
            "The One With The Kips",
            "The One With The Yeti",
            "The One Where Ross Moves In",
            "The One With All The Thanksgivings",
            "The One With Ross' Sandwich",
            "The One With The Inappropriate Sister",
            "The One With All The Resolutions",
            "The One With Chandler's Work Laugh",
            "The One With Joey's Bag",
            "The One Where Everybody Finds Out",
            "The One With The Girl Who Hits Joey",
            "The One With The Cop",
            "The One With Rachel's Inadvertent Kiss",
            "The One Where Rachel Smokes",
            "The One Where Ross Can't Flirt",
            "The One With The Ride-Along",
            "The One With The Ball",
            "The One With Joey's Big Break",
            "The One In Vegas, Part 1",
            "The One In Vegas, Part 2"
        ]

        self.s_5_original_airdate = [
            "September 24, 1998", "October 1, 1998", "October 8, 1998",
            "October 15, 1998", "October 29, 1998", "November 5, 1998",
            "November 12, 1998", "November 19, 1998", "December 10, 1998",
            "December 17, 1998", "January 7, 1999", "January 21, 1999",
            "February 4, 1999", "February 11, 1999", "February 18, 1999",
            "February 25, 1999", "March 18, 1999", "April 8, 1999",
            "April 22, 1999", "April 29, 1999", "May 6, 1999",
            "May 13, 1999", "May 20, 1999", "May 20, 1999"
        ]

        self.s_5_summary = [
            "Ross's nuptials continue after his slip-of-the-tongue but wedded bliss doesn't follow. Monica and Chandler try continuing their affair but can't steal a moment alone.",
            "Ross's attempts at reconciling with Emily go unheeded. Chandler and Monica's affair is challenged by their " + ' "Not-in-New York" ' + " rule.",
            "Phoebe is rushed to the hospital, where triplets are born. Joey gets hospitalized next - when his sympathy labor pains turn out to be kidney stones. An unsuspecting Rachel arranges a date for Monica with a male nurse.",
            "Phoebe resents Joey's PBS telethon gig because of a long-running grudge she holds against the network. To cover up her affair with Chandler, Monica tells Rachel she's dating someone from work.",
            "Monica and Chandler go to Atlantic City for a weekend by themselves. Ross tries to tell Rachel they can't be friends once Emily arrives in New York.",
            "While rummaging in the storage room, Monica and Rachel meet a hairy neighbor they first mistake for a yeti. To smooth things over with Emily, Ross agrees to de-Rachelize his apartment.",
            "With his marriage on the rocks, Ross moves in with Chandler and Joey. Rachel is convinced that her neighbor Danny is trying to seduce her with mind games.",
            "The gang reminisces about their worst Thanksgivings. Phoebe's takes her back to 1862. Elaborate tales are spun to try and uncover Monica's worst memory.",
            "Ross is enraged when someone at work steals his Thanksgiving leftovers sandwich. Joey threatens to crack under the strain of knowing about Monica and Chandler's affair.",
            "Monica maneuvers Rachel and Danny into dating but Rachel has second thoughts after observing Danny's unusually close relationship with his sister.",
            "As the new year approaches, everyone makes resolutions, some more realistic than others. Ross's resolution causes him to wear hot leather pants on a date...perhaps too hot.",
            "Monica uncovers the fake laugh Chandler reserves for his boss's bad jokes. Rachel is upset that Monica hasn't 'fessed up about her affair. Word comes of Emily's remarriage plans.",
            "When Rachel helps Joey change his image to help him land an acting gig, she includes a shoulder bag that's rather purselike. Phoebe is shocked when her dad attends her grandmother's funeral.",
            "When Phoebe finds out about the Monica/Chandler affair, she tests Chandler via flirtation. Ugly Naked Guy's apartment goes up for rent and Ross wants it.",
            "When Joey starts dating Katie, he finds she packs a painful punch. Ross has trouble making friends with his new neighbors.",
            "Phoebe finds a police badge inside the Central Perk sofa. Rather than return it, she decides to embark on a" + " good-deeds " + "campaign. Joey is unnerved by his romantic dream about Monica.",
            "After a job interview, Rachel impulsively kisses her potential boss on the cheek. Joey tries to find a hot girl who lives in Ross' apartment but instead ending up in Ross' apartment. Phoebe and Gary vie for" + ' "steamiest-affair" ' + "with Monica and Chandler.",
            "Rachel takes up smoking at her new job as a way of making inroads with the boss. Ross' son Ben joins Joey on an audition for a soup commerical.",
            "Joey's Italian-speaking grandma joins the gang in watching his Law & Order debut. Ross decides to order lots and lots of pizza in order to flirt with the delivery girl.",
            "As Emily's wedding nears, the group does its best to distract Ross. A gunshot and a meatball sandwich take center stage when the guys go out on the beat with Phoebe's cop boyfriend.",
            "Phoebe asks Chandler to talk Gary out of asking her to move in with him. To fulfill a childhood dream, Rachel buys a sphinx cat which doesn't behave as planned.",
            "Joey is excited about landing a lead role in a movie shooting just outside Las Vegas - but furious with Chandler after he confesses his doubts that it will be his" + ' "big break." ' + "Rachel's right eye is itchy and Monica takes her to the doctor who tells her to take eye drops. But however, Rachel is terrified to take the eye-drops.",
            "After his film gig falls through, Joey begs Chandler not to visit. But when Monica decides to celebrate her one-year anniversary with Chandler in Vegas, no one wants to be left behind.",
            "Joey tries to convince a blackjack dealter with identical hands to join him in a business venture. While playing craps with Monica, Chandler makes the bet of a lifetime."
        ]

        self.s_6_titles = [
            "The One After Vegas",
            "The One Where Ross Hugs Rachel",
            "The One With Ross' Denial",
            "The One Where Joey Loses His Insurance",
            "The One With Joey's Porsche",
            "The One On The Last Night",
            "The One Where Phoebe Runs",
            "The One With Ross' Teeth",
            "The One Where Ross Got High",
            "The One With The Routine",
            "The One With The Apothecary Table",
            "The One With The Joke",
            "The One With Rachel's Sister",
            "The One Where Chandler Can't Cry",
            "The One That Could Have Been, Part 1",
            "The One That Could Have Been, Part 2",
            "The One With Unagi",
            "The One Where Ross Dates A Student",
            "The One With Joey's Fridge",
            "The One With Mac And C.H.E.E.S.E.",
            "The One Where Ross Meets Elizabeth's Dad",
            "The One Where Paul's The Man",
            "The One With The Ring",
            "The One With The Proposal, Part 1",
            "The One With The Proposal, Part 2"
        ]

        self.s_6_original_airdate = [
            "September 23, 1999", "September 30, 1999", "October 7, 1999",
            "October 14, 1999", "October 21, 1999", "November 4, 1999",
            "November 11, 1999", "November 18, 1999", "November 25, 1999",
            "December 16, 1999", "January 6, 2000", "January 13, 2000",
            "February 3, 2000", "February 10, 2000", "February 17, 2000",
            "February 17, 2000", "February 24, 2000", "March 9, 2000",
            "March 23, 2000", "April 13, 2000", "April 27, 2000",
            "May 4, 2000", "May 11, 2000", "May 18, 2000",
            "May 18, 2000"
        ]

        self.s_6_summary = [
            "A hungover Ross and Rachel are shocked to discover they are husband and wife. Joey and Phoebe have a cross-country adventure.",
            "When Monica and Chandler tell Rachel that they are moving in together, she mistakenly believes that all three will be roommates. Phoebe discovers that Ross hasn't annulled his marriage to Rachel.",
            "Monica and Chandler argue about what to do with Rachel's room after she moves out. Ross suggests that Rachel move in with him.",
            "Joey gets a hernia just as he learns his health insurance has lapsed. When a psychic predicts she'll die within a week, Phoebe plans to make the most of her final days.",
            "Joey finds keys to a Porsche and pretends the car is his to impress women. Rachel tries to have her marriage to Ross annulled on the basis of his mental instability.",
            "While boxing up Rachel's belongings, the girls reminisce about their time spent as roommates. Joey's pride forces Chandler to invent a creative way to lend him money.",
            "Phoebe's unorthodox, attention-getting jogging style embarrasses running mate Rachel. Chandler tries to surprise Monica by cleaning the apartment but forgets where everything goes therefore, seeking help from Ross. Joey's new roommate, a dancer from Australia, moves in with him.",
            "Rumor has it that Rachel's boss Ralph Lauren made a romantic pass at Phoebe. Ross has a " +' "bright" ' + "idea to impress his date.",
            "Monica hosts Thanksgiving and Chandler uses the occasion to try and win her parents over. Rachel tests her confused culinary skills on dessert.",
            "Joey, Ross and Monica attend a taping of Dick Clark's New Year's Rockin' Eve. Joey has special plans for his roommate Janine at the midnight hour.",
            "After double-dating, Joey learns of Janine's dislike for Monica and Chandler. Rachel tries to convince Phoebe that her cute new apothecary table is a priceless antique.",
            "When Ross gets a joke printed in Playboy, Chandler claims credit for it. Joey reluctantly takes a job as a waiter at Central Perk.",
            "When her sister Jill visits, Rachel worries about the sparks that seem to fly between her and Ross. Monica tries to seduce Chandler, despite having the flu.",
            "Rachel forces Ross to cancel his date with her sister. Phoebe discovers she's being mistaken for a porn star. Chandler admits he hasn't been able to cry since he was a child.",
            "The gang ponders what might have been if: Ross had stayed with his lesbian wife; a married Rachel had fallen for Days of Our Lives star Joey; a portly Monica had been obsessed with losing her virginity; Chandler had been a struggling writer; and Phoebe had been a stockbroker.",
            "The gang ponders what might have been if: Ross had stayed with his lesbian wife; a married Rachel had fallen for Days of Our Lives star Joey; a portly Monica had been obsessed with losing her virginity; Chandler had been a struggling writer; and Phoebe had been a stockbroker.",
            "Ross tries to teach martial arts to Rachel and Phoebe. Joey hires a look-alike to pose as his twin brother for a medical experiment.",
            "Ross flirts with danger when he dates an attractive student. After a fire damages their apartment, Rachel and Phoebe are forced to move in with their friends.",
            "When Rachel needs a date for a charity event, Monica and Phoebe compete to find her the best escort. Ross obsesses about his girlfriend spending spring break in Florida. Joey's refrigerator breaks.",
            "Joey gets an audition for the lead in a TV show, which sparks memorable and bizarre flashbacks for the gang.",
            "Ross dreads meeting his college girlfriend's disapproving father. When Joey insults his robot co-star, he jeopardizes his future on the show.",
            "Despite Paul's threats, Ross and Elizabeth secretly head off to her family's mountain cabin. Paul and Rachel have exactly the same plan.",
            "Chandler asks Phoebe's help in choosing a ring for Monica. Rachel regrets pushing Paul to express his feelings.",
            "The big evening has arrived, but Chandler's romantic plans are ruined when Monica's ex-boyfriend appears. Things sail way off course when Rachel, Phoebe and Joey attend a charity auction. Due to the friends thinking that Ross' relationship with Elizabeth is not going anywhere, he breaks up with her.",
            'Rachel and Phoebe arrange "backups". Chandler tries to win Monica back after he fears he ruined things.'
        ]

        self.s_7_titles = [
            "The One With Monica's Thunder",
            "The One With Rachel's Book",
            "The One With Phoebe's Cookies",
            "The One With Rachel's Assistant",
            "The One With The Engagement Picture",
            "The One With The Nap Partners",
            "The One With Ross' Library Book",
            "The One Where Chandler Doesn't Like Dogs",
            "The One With All The Candy",
            "The One With The Holiday Armadillo",
            "The One With All The Cheesecakes",
            "The One Where They're Up All Night",
            "The One Where Rosita Dies",
            "The One Where They All Turn Thirty",
            "The One With Joey's New Brain",
            "The One With The Truth About London",
            "The One With The Cheap Wedding Dress",
            "The One With Joey's Award",
            "The One With Ross And Monica's Cousin",
            "The One With Rachel's Big Kiss",
            "The One With The Vows",
            "The One With Chandler's Dad",
            "The One With Monica And Chandler's Wedding, Part 1",
            "The One With Monica And Chandler's Wedding, Part 2"
        ]

        self.s_7_original_airdate = [
            "October 5, 2000", "October 12, 2000", "October 19, 2000",
            "October 26, 2000", "November 2, 2000", "November 9, 2000",
            "November 16, 2000", "November 23, 2000", "December 7, 2000",
            "December 14, 2000", "January 4, 2001", "January 11, 2001",
            "February 1, 2001", "February 8, 2001", "February 15, 2001",
            "February 22, 2001", "March 15, 2001", "March 29, 2001",
            "April 19, 2001", "April 26, 2001", "May 3, 2001",
            "May 10, 2001", "May 17, 2001", "May 17, 2001"
        ]

        self.s_7_summary = [
            "Minutes after Chandler proposes to Monica, she plans to celebrate on the town with he pals - until she catches Ross and Rachel kissing.",
            "Monica's dream of elaborate nuptials fizzles when she learns what her parents have done with her wedding fund. Rachel is embarrassed when a teasing Joey stumbles onto her juicy, late-night reading material.",
            "Chandler's bonding attempt with his future father-in-law during a close sauna encounter backfires. Monica tries to replicate Phoebe's grandmother's secret cookie recipe by deconstructing her one last cookie.",
            "When Rachel is promoted, she gleefully considers hiring an inexperienced hunk as her executive assistant. In a free-for-all tell-all game, Chandler and Monica expose humiliating secrets from each other's pasts.",
            "Unphotogenic Chandler can't get a good photo taken with Monica. Rachel plans to get closer to her hunky assistant by encouraging him to hang out with Joey, but the plan sours when he picks up on Joey's moves.",
            "Monica frets when she meets one of Chandler's long-lost girlfriends and learns that he dumped her because she was fat. Phoebe and Rachel vie for the honor of becoming Monica's bridesmaid.",
            "When Joey decides to stop dating a girl that Rachel and Phoebe have come to adore, the ladies take action to change his mind. Ross fumes when he discovers the location of his dissertation in the university library.",
            "A beaming Rachel is happily surprised when her assistant Tag shows up at the gang's Thanksgiving dinner. Phoebe sneaks a puppy into the apartment, forcing Chandler to confess why he hates dogs.",
            "Monica whips up some holiday candy for the neighbors. Rachel and Tag set the ground rules for their new romance. Moved by Phoebe's bikeless childhood story, Ross buys her a new two-wheeler.",
            "Ross wants to introduce son Ben to Hanukkah. In order to entice Rachel to move back into their refurbished apartment, Phoebe must drive a wedge between Rachel and current roomie Joey.",
            "Phoebe's old flame David visits from Russia for an evening of romance. Rachel and Chandler swipe deliveries of a particularly tasty cheesecake from their neighbor's doorstep.",
            "Rachel and Tag's first night together is put on hold when they realize they forgot to overnight an important package. Ross and Joey are stuck on the roof and Phoebe can't disable a relentlessly beeping smoke alarm. Monica and Chandler cannot get to sleep.",
            "Phoebe has a bizarre first day in her new job when she encounters a distraught office manager in a suicidal mood. Rachel and Chandler both believe they have broken Joey's favorite chair.",
            "Rachel's agony over her 30th birthday starts everyone reminiscing about what they did upon reaching that milestone.",
            "Joey accidentally lets slip to a Days of Our Lives castmate that she is being written out of the script. Rachel and Phoebe try to sabotage each other's chances to date a guy who left his cell phone at Central Perk.",
            "Monica and Chandler grudgingly agree to let Joey marry them - once he's been" + ' "ordained" ' + "via the Internet. While babysitting, Rachel teaches Ben a few practical jokes.",
            "Monica regrets telling a fellow bride-to-be about a cheaper bridal store when she has to fight her tooth-and-nail for a unique wedding dress - and later the right to hire Chandler's favorite band for the event!",
            "Joey is overjoyed to be nominated for a" + ' "Soapie". ' + "Monica gets wedding jitters.",
            "When Monica and Ross's alluring cousin visits, her irresistible beauty causes serious distractions for all the men who meet her. Rachel and Phoebe try to rush their plans for Monica's shower.",
            "Rachel bumps into her old sorority sister and wonders whether she should confront her about a night in college when their friendship took a passionate turn.",
            "Writing their wedding vows proves a daunting task for Monica and Chandler. Looking back over the pair's relationship, the other friends worry about changes in store for all of them.",
            "Monica arranges a meeting between Chandler and his estranged dad in hopes that they can reconcile before the ceremony. Rachel and a reluctant Ross borrow the keys to Monica's Porsche.",
            "Monica and Chandler gather their offbeat families on the eve of their wedding but there's one problem: Chandler is missing. While Ross searches for him, Rachel and Phoebe desperately try to distract the unsuspecting bride.",
            "Monica and Chandler get married. Someone is hiding a big surprise."
        ]

        self.s_8_titles = [
            'The One After "I Do"',
            "The One With The Red Sweater",
            "The One Where Rachel Tells...",
            "The One With The Videotape",
            "The One With Rachel's Date",
            "The One With The Halloween Party",
            "The One With The Stain",
            "The One With The Stripper",
            "The One With The Rumor",
            "The One With Monica's Boots",
            "The One With Ross's Step Forward",
            "The One Where Joey Dates Rachel",
            "The One Where Chandler Takes A Bath",
            "The One With The Secret Closet",
            "The One With The Birthing Video",
            "The One Where Joey Tells Rachel",
            "The One With The Tea Leaves",
            "The One In Massapequa",
            "The One With Joey's Interview",
            "The One With The Baby Shower",
            "The One With The Cooking Class",
            "The One Where Rachel Is Late",
            "The One Where Rachel Has A Baby, Part 1",
            "The One Where Rachel Has A Baby, Part 2"
        ]

        self.s_8_original_airdate = [
            "September 27, 2001", "October 4, 2001", "October 11, 2001",
            "October 18, 2001", "October 25, 2001", "November 1, 2001",
            "November 8, 2001", "November 15, 2001", "November 22, 2001",
            "December 6, 2001", "December 13, 2001", "January 10, 2002",
            "January 17, 2002", "January 31, 2002", "February 7, 2002",
            "February 28, 2002", "March 7, 2002", "March 28, 2002",
            "April 4, 2002", "April 25, 2002", "May 2, 2002",
            "May 9, 2002", "May 16, 2002", "May 16, 2002"
        ]

        self.s_8_summary = [
            "Monica and Chandler's wedding reception is almost upstaged by the news that someone may be pregnant. Phoebe suspects its Rachel and comes up with a plan to cover for her friend.",
            "Monica and Phoebe speculate about who might be the father of Rachel's baby. Mistakenly thinking Phoebe is the one who's pregnant, Joey makes a gallant gesture.",
            "Everybody seems to know who the father of Rachel's baby is, except the guy himself: Ross. Phoebe and Joey fib about a gas leak to gain entry to Monica and Chandler's apartment.",
            "Ross and Rachel's attempt to explain how they wound up getting pregnant turns into an argument over who came on to whom - until Ross makes the shocking announcement that he has the encounter on videotape.",
            "Ross is horrified to learn that the pregnant Rachel is headed out on a date with a handsome actor, while Phoebe protests when Monica wants to fire a cute but clumsy sous-chef whom she fancies.",
            "At Monica's Halloween party, Phoebe meets her twin sister Ursula's fiance and finds herself attracted to him as well.",
            "Ross learns Rachel wants to move out and find her own place... and suggests a vacancy in his building. But Joey gives Ross tough competition when he puts a nursery in their apartment to make her stay.",
            "Feeling guilty for denying Chandler a reach bachelor party, Monica arranges for a stripper to perform for him, but Chandler's in for a big surprise.",
            "Monica bumps into an old high school friend and invites him to Thanksgiving dinner with the gang - unaware that he isn't exactly fond of Rachel.",
            "Chandler is peeved when Monica splurges on an expensive pair of boots. When Phoebe learns Ross's and Sting's children attend the same school, she angles to meet the celebrity and get concert tickets.",
            "Ross becomes nervous when Mona wants to mail a joint Christmas card with the couple's picture. As the hormonal effects of her pregnancy kick in, Rachel searches for possible romantic partners - such as Joey.",
            "To prepare Joey for a big date, Rachel goes out with him for a night on the town. But things take an unexpected turn: the date is a success and Joey becomes intensely attracted to Rachel.",
            "Joey is crazy with guilt over his newfound affection for Rachel - and things get screwier when Monica mistakenly thinks he's infatuated with Phoebe.",
            "Chandler becomes obsessed with finding out what is behind the locked door of Monica's forbidden closet. Phoebe feels betrayed when she discovers Monica has been using another massage therapist.",
            "Monica goes all out for Valentine's Day with sexy lingerie and X-rated entertainment. But Chandler is too shell-shocked to respond after he accidentally watches a birthing video meant for Rachel.",
            "Joey tells Ross about his true feelings for Rachel. They agree that Joey should tell Rachel during dinner, regardless of the consequences. Chandler fears that Phoebe's new boyfriend Don may be more compatible with Monica than he is.",
            "Phoebe determine through reading tea leaves that she'll soon meet the man of her dreams. Feeling awkward after revealing his true feelings for Rachel, Joey keeps a low profile.",
            "Monica regrets her request to supplant Ross as the designated toast-giver at their parents' 35th wedding anniversary. Phoebe's latest boyfriend drives everyone at the party crazy with his upbeat optimism.",
            "Joey is thrilled when his name is used in a Soap Opera Digest crossword. But he's reluctant for them to do a profile of him because his last interview got him into so much trouble he was written out of the show.",
            "Rachel panics that she is unprepared to care for a newborn and reluctantly goes along with her mother's plans to move in and help out - which hardly makes roommate Ross jump for joy.",
            "Monica's restaurant is hit with a bad review, and she drags Joey along to a class taught by the critic in the hope of changing his mind. While shopping for baby gear, Rachel is put out when a salesgirl flirts with Ross.",
            "An overdue Rachel will try anything to get the baby moving. Joey is ticked off when Chandler nods off during he screening of his new movie.",
            "Rachel's baby nears delivery with an anxious Ross nearby. While she's in endless labor hell, her waiting friends cause hospital havoc. Chandler and Monica search for privacy in a quest to have their own baby.",
            "Rachel has her baby and names her Emma. Joey finds Ross's ring and Rachel thinks Joey is proposing to her!"
        ]

        self.s_9_titles = [
            "The One Where No One Proposes",
            "The One Where Emma Cries",
            "The One With The Pediatrician",
            "The One With The Sharks",
            "The One With Phoebe's Birthday Dinner",
            "The One With The Male Nanny",
            "The One With Ross' Inappropriate Song",
            "The One With Rachel's Other Sister",
            "The One With Rachel's Phone Number",
            "The One With Christmas In Tulsa",
            "The One Where Rachel Goes Back To Work",
            "The One With Phoebe's Rats",
            "The One Where Monica Sings",
            "The One With The Blind Dates",
            "The One With The Mugging",
            "The One With The Boob Job",
            "The One With The Memorial Service",
            "The One With The Lottery",
            "The One With Rachel's Dream",
            "The One With The Soap Opera Party",
            "The One With The Fertility Test",
            "The One With The Donor",
            "The One In Barbados, Part 1",
            "The One In Barbados, Part 2"
        ]

        self.s_9_original_airdate = [
            "September 26, 2002", "October 3, 2002", "October 10, 2002",
            "October 17, 2002", "October 31, 2002", "November 7, 2002",
            "November 14, 2002", "November 21, 2002", "December 5, 2002",
            "December 12, 2002", "January 9, 2003", "January 16, 2003",
            "January 30, 2003", "February 6, 2003", "February 13, 2003",
            "February 20, 2003", "March 13, 2003", "April 3, 2003",
            "April 17, 2003", "April 24, 2003", "May 1, 2003",
            "May 8, 2003", "May 15, 2003", "May 15, 2003"
        ]

        self.s_9_summary = [
            "Due to a misunderstanding, Rachel finds herself engaged to Joey instead of Ross. Things get more confused when Phoebe mistakenly assumes that Ross is the one who proposed.",
            "Joey's attempts to gain Ross's forgiveness for mistakenly asking Rachel to marry him only result in emergency hospitalization. A weary Rachel seeks any remedy to quell baby Emma's nonstop crying.",
            "Rachel's constant calls to her pediatrician force him to drop Emma as a patient. Ross becomes uncomfortable when Rachel seeks his childhood doctor as a replacement - mainly because he is still Ross's doctor.",
            "Worried she may lose her latest boyfriend, Phoebe's self-doubt is worsened by Ross's foolish comments. Monica mistakenly fears Chandler has an unnatural fetish for sharks.",
            "While Phoebe and Joey await their friends at a fancy restaurant, Rachel frets about leaving Emma with a sitter. Monica and Chandler are also running late due to a heated spat.",
            "Rachel's choice of an oversensitive male nanny sparks Ross's mockery. Phoebe must choose between two ardent suitors: new boyfriend Mike or visiting former boyfriend David.",
            "When Chandler's former romantic rival intends to sell his apartment, Chandler and Joey secretly inspect it...and make a shocking discovery. Ross discovers that singing rap is the only way to get baby Emma to laugh.",
            "On the night before Thanksgiving, Rachel's self-centered younger sister Amy ruins everyone's holiday dinner with her uncensored observations.",
            "While out with Phoebe, Rachel impulsively gives a handsome guy her phone number - then worries he'll call when Ross is in. Mike and Ross desperately try finding something to talk about while baby-sitting Emma.",
            "Chandler must stay in Tulsa over Christmas due to work deadlines. Monica suspects the worst when she learns that his beautiful co-worker Wendy will join him.",
            "Rachel meets her handsome rival Gavin, who has covered her job while she's been on maternity leave. Their immediate war of wills prompts her to make a rash decision that she could regret. Meanwhile, Phoebe works as an extra on Days Of Our Lives",
            "Rachel is peeved to learn that Gavin is invited to her birthday party. Ross struggles to keep lascivious Joey away from Emma's beautiful new nanny. Phoebe coaxes Mike into helping care for a litter of baby rats.",
            "As Rachel sorts out her feelings for Gavin, Ross recruits Chandler to help him meet attractive women to make her jealous. Monica's see-through dress is a big hit when Phoebe brings her to karaoke night!",
            "Joey and Phoebe conspire to arrange awful dates for both Rachel and Ross, hoping that appreciation of their former relationship will cause them to reunite.",
            "To impress a pompous fellow actor during an audition, Joey develops an unusual acting method. Ross is horrified to discover who mugged him when he was a child.",
            "Phoebe asks Mike to move in with her, but coming so close to married life may spell trouble. The financially strapped Monica and Chandler separately and unknowingly ask Joey for loans.",
            "When Chandler jokingly posts an outrageous biography of Ross on his college alumni website, Ross retaliates in similar fashion - triggering an Internet war between the two friends.",
            "Hoping to win a huge jackpot, the friends pool their cash and buy dozens of lottery tickets. But bickering over how to spend potential winnings and other disagreements cause a lotto tension.",
            "Nervous about an upcoming romantic scene, Joey rehearses with Rachel. After watching the show's taping, Rachel has a surprising dream about Joey.",
            "Ross is excited when his paleontology colleague Charlie is also a stunning beauty. But the excitement fades when she discusses her impressive list of ex-boyfriends at Joey's rooftop party for his Days of Our Lives castmates.",
            "Ross is hurt when brilliant Charlie starts dating shallow Joey. However, Joey asks him for advice on how to impress her. Meanwhile, Chandler and Monica have a chance encounter at a fertility clinic.",
            "Sad to learn that they cannot conceive naturally, Monica and Chandler mull their options. Chandler brings home a handsome, unknowing co-worker for dinner to" + ' "interview" ' + "him as a potential sperm donor. After deciding that having a sperm donor is not right for them, they decide to adopt.",
            "Ross procures free passes for his friends to a paleontologists' convention in Barbados, then scrambles to reconstruct - with Charlie's help - his keynote address after its accidental erasure from his computer. Mike arrives to win Phoebe back.",
            "Monica and Mike play a heated game of ping pong. Rachel can't hide her feelings for Joey any longer..."
        ]

        self.s_10_titles = [
            "The One After Joey And Rachel Kiss",
            "The One Where Ross Is Fine",
            "The One With Ross' Tan",
            "The One With The Cake",
            "The One Where Rachel's Sister Baby-Sits",
            "The One With Ross' Grant",
            "The One With The Home Study",
            "The One With The Late Thanksgiving",
            "The One With The Birth Mother",
            "The One Where Chandler Gets Caught",
            "The One Where The Stripper Cries",
            "The One With Phoebe's Wedding",
            "The One Where Joey Speaks French",
            "The One With Princess Consuela",
            "The One Where Estelle Dies",
            "The One With Rachel's Going Away Party",
            "The Last One, Part 1",
            "The Last One, Part 2"
        ]

        self.s_10_original_airdate = [
            "September 25, 2003", "October 2, 2003", "October 9, 2003",
            "October 23, 2003", "October 30, 2003", "November 6, 2003",
            "November 13, 2003", "November 20, 2003", "January 8, 2004",
            "January 15, 2004", "February 5, 2004", "February 12, 2004",
            "February 19, 2004", "February 26, 2004", "April 22, 2004",
            "April 29, 2004", "May 6, 2004", "May 6, 2004"
        ]

        self.s_10_summary = [
            "Romantic hookups continue to go astray in Barbados as Monica, Phoebe and Chandler overhear Ross kissing Charlie, while through the room's other wall they can eavesdrop on Joey and Rachel.",
            "Rachel, Joey and Charlie spend an uncomfortable evening with Ross while Chandler commits an unpardonable act when he and Monica visit a couple who have adopted a cute boy. Phoebe is visited by a desperate Frank Jr., who can't cope with his triplets.",
            "Rachel and Joey nervously anticipate their first real" + ' "night" ' + "together. Monica and Phoebe try to avoid an obnoxious old friend who puts on airs and a fake accent. Ross envies Monica's sprayed-on tan and enters the tanning booth, where two-toned disaster strikes.",
            "Rachel convinces Monica to delay a long anticipated trip to Vermont. But complications ensue when an X-rated birthday cake arrives.",
            "Rachel convinces spoiled sister Amy to baby-sit Emma over Ross's protests. Phoebe unknowingly thwarts Mike's surprise for her. Joey scares Monica and Chandler with a recommendation letter on their behalf to a child adoption agency.",
            "Ross interviews with a Nobel Prize-winning scientist for a paleontology grant - but the doctor is Charlie's ex-boyfriend, who offers Ross the grant only if he breaks up with her. Phoebe sends Monica and Rachel screaming with her artistic creation of" + ' "Gladys".',
            "Monica and Chandler meet with an adoption worker who will decide if they're suitable parents - and who confesses that she was once romanced by a cad named Joey in the same building.",
            "Monica prepares a Thanksgiving feast and is furious when no one shows up! When Joey gets stuck in the door, Monica and Chandler have the ideal remedy. Phoebe convinces Rachel to enroll Emma in a baby beauty contest.",
            "Monica and Chandler travel to Texas to meet a young pregnant woman who is considering allowing them to adopt her child when it's born. Joey dates Phoebe's friend but annoys her with his territorial eating habits.",
            "When Phoebe and Rachel see Chandler getting into a car with a pretty woman, they suspect the worst. When they tell Monica, they learn the woman is a real estate agent - and that the couple's been house-hunting outside Manhattan.",
            "Joey is a celebrity guest on Pyramid. When Monica and Rachel throw a" + ' "mature" ' + "bachelorette party for Phoebe, they're forced to hire a stripper at the last minute. Chandler and Ross attend their college reunion, where they learn a 1987 dating pact was broken.",
            "Monica's hard-nosed wedding-planner techniques cause Phoebe to fire her. The big day turns chaotic when a blizzard forces a change in plans.",
            "When Phoebe tries teaching Joey to speak French for an audition and fails, she convinces the casting director Joey is retarded. Ross turns down Rachel's request for sympathy sex after her father has a heart attack.",
            "Rachel is fired from her job the same day Ross learns that he has gotten tenure. When Phoebe legally changes her name, Mike does so too to teacher her a lesson. Joey goes with Chandler and Monica to check out their new home.",
            "Phoebe tries to protect Joey from the news that his agent Estelle has died. Monica and Chandler check out the house next door to theirs - and discover that Chandler's ex-girlfriend Janice is interested in buying it.",
            "Ross goes berserk when Rachel decides that Monica's farewell party is the perfect time to share a private, tearful goodbye with each friend - with the single exception of Ross!",
            "Set to embark on the next chapters in their lives, the six friends spend their last day together, and it's one of the momentous events, major decisions about personal futures and last-minute surprises. Part 1 of 2.",
            "Set to embark on the next chapters in their lives, the six friends spend their last day together, and it's one of the momentous events, major decisions about personal futures and last-minute surprises. Part 2 of 2."
        ]